### ISSUE TITLE
Issue when Running "tsc telegram-backend.ts"

### ISSUE THREAD

**Issue by mohamedkaissi** [greengeckowizard/RcloneTelegram#1]
https://pastebin.com/pNKg6ra7

**Comment by fe80Grau** [comment]
run next command 
```
npm install rclone
```
and replace last main() invoke by startServer();


Probably when you compile and run server with node telegram-backend.js command you will get an error, this is because esModuleINterop is false. Create a new file named tsconfig.json and put next content
```
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true
  },
  "files": [
    "telegram-backend.ts"
  ]
}
```

To recompile using tsconfig.json run next command

```
tsc --project tsconfig.json
```

Then server still will working if you run 
```
node telegram-backend.js
```

**Comment by greengeckowizard** [comment]
> run next command
> 
> ```
> npm install rclone
> ```
> 
> and replace last main() invoke by startServer();
> 
> Probably when you compile and run server with node telegram-backend.js command you will get an error, this is because esModuleINterop is false. Create a new file named tsconfig.json and put next content
> 
> ```
> {
>   "compilerOptions": {
>     "module": "commonjs",
>     "esModuleInterop": true
>   },
>   "files": [
>     "telegram-backend.ts"
>   ]
> }
> ```
> 
> To recompile using tsconfig.json run next command
> 
> ```
> tsc --project tsconfig.json
> ```
> 
> Then server will works if you run
> 
> ```
> node telegram-backend.js
> ```

If your fine could you add these in a pull request please and thank you.

**Comment by greengeckowizard** [comment]
> run next command
> 
> ```
> npm install rclone
> ```
> 
> and replace last main() invoke by startServer();
> 
> Probably when you compile and run server with node telegram-backend.js command you will get an error, this is because esModuleINterop is false. Create a new file named tsconfig.json and put next content
> 
> ```
> {
>   "compilerOptions": {
>     "module": "commonjs",
>     "esModuleInterop": true
>   },
>   "files": [
>     "telegram-backend.ts"
>   ]
> }
> ```
> 
> To recompile using tsconfig.json run next command
> 
> ```
> tsc --project tsconfig.json
> ```
> 
> Then server will works if you run
> 
> ```
> node telegram-backend.js
> ```

That's right sorry I'll add
