### ISSUE TITLE
how to define telegram type in rclone?

### ISSUE THREAD

**Issue by fe80Grau** [greengeckowizard/RcloneTelegram#3]
Hi, 
congrats for your work. I'm trying to understand how to add telegram as backend in rclone command https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend 

Do you have any reference from another backend implementation? If you don't have time doesn't matter i can read and try more or wait to production release.

**Comment by greengeckowizard** [comment]
> Hi, congrats for your work. I'm trying to understand how to add telegram as backend in rclone command https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend
> 
> Do you have any reference from another backend implementation? If you don't have time doesn't matter i can read and try more or wait to production release.

Maybe try to add the rclone config to rclone. I'm still learning more about rclone as it's still newer to me. I kinda just went off this https://forum.rclone.org/t/what-is-needed-to-create-a-new-backend/19647

**Comment by greengeckowizard** [comment]
> Ty dude, i will try to copy pcloud backend https://github.com/rclone/rclone/tree/master/backend/pcloud and edit it with your server endpoints.
> 
> I'll tell you soon

Awesome thank you very much 😊

**Comment by greengeckowizard** [comment]
I switch to Go since all the other backends use go.
