### ISSUE TITLE
compile, Cannot find name 'rclone', express

### ISSUE THREAD

**Issue by skygunner** [greengeckowizard/RcloneTelegram#4]
```shell
 tsc --project tsconfig.json 
telegram-backend.ts:93:26 - error TS2304: Cannot find name 'rclone'.

93       const client = new rclone.Client();
                            ~~~~~~

telegram-backend.ts:115:26 - error TS2304: Cannot find name 'rclone'.

115       const client = new rclone.Client();
                             ~~~~~~


Found 2 errors in the same file, starting at: telegram-backend.ts:93

```

The compile command complains about can't find express, rclone. 
Installing express with 
npm install express
 solves that part. 
What package do I need for rclone? Tried 
npm install rclone
and other similar named packages, does not work.

**Comment by Abhijith4124** [comment]
Having the same issue here...

**Comment by greengeckowizard** [comment]
Can you try this npm install @types/rclone I haven't tested that to see If it worked please let me know if it resolves the error.

**Comment by skygunner** [comment]
nope ,
'@types/rclone@*' is not in this registry

**Comment by Abhijith4124** [comment]
Importing rclone works

import { rclone, Config } from 'rclone';

**Comment by greengeckowizard** [comment]
I switch to Go since all the other backends use go.
